<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>Core;Cli</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Exe.targets" />

  <PropertyGroup>
    <AssemblyName>showkeys</AssemblyName>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
