<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>Core;Docopt</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Exe.targets" />

  <PropertyGroup>
    <AssemblyName>stale</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);ENABLE_TASK_CREATION_TRACKING</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' != 'Debug' ">
    <PublishReadyToRun>true</PublishReadyToRun>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="BannedSymbols.txt" />
    <ProjectReference Include="..\Core.Terminal\Core.Terminal.csproj" />
    <PackageReference Include="Dumpify" />
    <PackageReference Include="Spectre.Console" />

    <PackageReference Include="Vezel.Cathode" />
    <!--Reference Include="C:\proj\ok\_research\Vezel.Cathode\out\obj\src\core\release\Vezel.Cathode.dll"/>
    <Reference Include="C:\proj\ok\_research\Vezel.Cathode\out\bin\src\common\release\Vezel.Cathode.Common.dll"/>
    <Reference Include="C:\proj\ok\_research\Vezel.Cathode\out\bin\src\native\debug_win-x64\Vezel.Cathode.Native.dll"/-->

  </ItemGroup>

</Project>
