<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>Core;Docopt</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Exe.targets" />

  <PropertyGroup>
    <AssemblyName>stale</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' != 'Debug' ">
    <PublishReadyToRun>true</PublishReadyToRun>
    <SelfContained>true</SelfContained>
    <PublshTrimmed>true</PublshTrimmed>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dumpify" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Vezel.Cathode" />
  </ItemGroup>

</Project>
