<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>Core;Docopt</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Exe.targets" />

  <PropertyGroup>
    <AssemblyName>stale</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants Condition="'$(Configuration)'=='Debug'">ENABLE_SCREEN_RECORDER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dumpify" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Vezel.Cathode" />
  </ItemGroup>

</Project>
