<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>Core;Cli</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Exe.targets" />

  <PropertyGroup>
    <AssemblyName>pmltool</AssemblyName>
    <NoWarn>$(NoWarn);RS0030</NoWarn> <!-- not ready to convert to vezel yet -->
  </PropertyGroup>

  <ItemGroup>
    <None Update="Scripts\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(OkSrcRoot)ProcMonUtils\ProcMonUtils.csproj" />
  </ItemGroup>

</Project>
