<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>Core;NetMulti;BannedSymbols</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Library.targets" />

  <PropertyGroup>
    <RootNamespace>OkTools.Terminal</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn> <!-- just doing spot-docs -->

    <!-- because it's a package, avoid adding requirements -->
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
  </PropertyGroup>

  <!-- nuget -->
  <PropertyGroup>
    <GeneratePackageOnBuild>$(_IsPublishing)</GeneratePackageOnBuild>
    <Title>Some OK terminal utility functions</Title>
    <RepositoryUrl>https://github.com/scottbilas/OkTools</RepositoryUrl>
    <PackageVersion>1.0.3</PackageVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <!-- dependencies -->
  <ItemGroup>
    <PackageReference Include="docopt.net" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Vezel.Cathode" />
  </ItemGroup>

</Project>
