<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(OkTargetsRoot)Tests.targets" />

  <PropertyGroup>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier> <!-- match the main project (set in Exe.targets) -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dumpify" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(OkSrcRoot)Unity.Cli\Unity.Cli.csproj" />
    <ProjectReference Include="Unity.csproj">
      <Aliases>Unity</Aliases><!-- disambiguate `_Include`-ref'd files (TODO: find better way..this happens because of InternalsVisibleTo)-->
    </ProjectReference>
  </ItemGroup>

</Project>
