<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>T4;Net78</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Tests.targets" />

  <PropertyGroup>
    <!-- nunit won't test a netstandard dll https://stackoverflow.com/questions/48043023/how-can-i-get-nunit3testadapter-to-work-with-net-standard-2-0#comment85869899_48043394 -->
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
