<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>T4;NetMulti;BannedSymbols</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Library.targets" />

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>OkTools.Core</RootNamespace>
    <TargetFrameworks>$(TargetFrameworks);netstandard2.1</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn> <!-- just doing spot-docs -->
    <DefineConstants>$(DefineConstants);NICEIO_PUBLIC</DefineConstants>

    <!-- because it's a package, avoid adding requirements -->
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
  </PropertyGroup>

  <!-- nuget -->
  <PropertyGroup>
    <GeneratePackageOnBuild>$(_IsPublishing)</GeneratePackageOnBuild>
    <Title>Some OK core utility functions.</Title>
    <RepositoryUrl>https://github.com/scottbilas/OkTools</RepositoryUrl>
    <PackageVersion>1.1.4</PackageVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <!-- dependencies -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="OkTools.NiceIO" />
    <PreprocessorValue Include="NICEIO_NAMESPACE" Value="OkTools.Core" Visible="false" />

    <!-- this is needed to make the compiler happy for usage of 'dynamic' -->
    <PackageReference Include="Microsoft.CSharp" Condition="'$(TargetFramework)' == 'netstandard2.1'" />
  </ItemGroup>

  <!-- t4 (TODO: move into Library.targets, also get build-based gen working again)-->
  <ItemGroup>
    <None Update="WideTypes.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>WideTypes.cs</LastGenOutput>
    </None>
    <Compile Update="WideTypes.cs">
      <DependentUpon>WideTypes.tt</DependentUpon>
    </Compile>
    <None Update="Extensions\SpanExtensions.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SpanExtensions.cs</LastGenOutput>
    </None>
    <Compile Update="Extensions\SpanExtensions.cs">
      <DependentUpon>SpanExtensions.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
