<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OkFeatures>T4;NetMulti</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Library.targets" />

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>OkTools.Core</RootNamespace>
    <TargetFrameworks>$(TargetFrameworks);netstandard2.1</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <DefineConstants>$(DefineConstants);NICEIO_PUBLIC</DefineConstants>

    <!-- because it's a package, avoid adding requirements -->
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
  </PropertyGroup>

  <!-- nuget -->
  <PropertyGroup>
    <GeneratePackageOnBuild>$(_IsPublishing)</GeneratePackageOnBuild>
    <Title>Some OK core utility functions</Title>
    <RepositoryUrl>https://github.com/scottbilas/OkTools</RepositoryUrl>
    <PackageVersion>1.0.17</PackageVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="OkTools.Core" />
    <Using Include="OkTools.Core.Extensions" />

    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE.md" Pack="true" PackagePath="/" />
    <None Update="WideTypes.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>WideTypes.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="OkTools.NiceIO" />
    <PreprocessorValue Include="NICEIO_NAMESPACE" Value="OkTools.Core" Visible="false" />

    <!-- this is needed to make the compiler happy for usage of 'dynamic' -->
    <PackageReference Include="Microsoft.CSharp" Condition="'$(TargetFramework)' == 'netstandard2.1'" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="WideTypes.cs">
      <DependentUpon>WideTypes.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
