<Project Sdk="Microsoft.NET.Sdk">
  <!-- nunit won't test a netstandard dll https://stackoverflow.com/questions/48043023/how-can-i-get-nunit3testadapter-to-work-with-net-standard-2-0#comment85869899_48043394 -->
  <PropertyGroup><OkFeatures>Core;T4;NetMulti</OkFeatures></PropertyGroup>
  <Import Project="$(OkTargetsRoot)Tests.targets" />

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CA1311</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="SpanExtensions.t.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SpanExtensions.t.cs</LastGenOutput>
    </None>
    <Compile Update="SpanExtensions.t.cs">
      <DependentUpon>SpanExtensions.t.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
