name: Validate Dev Branch

on:
  push:
    branches: [ 'dev' ]

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - name: Checkout + submodules
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '7.0.x'

      # https://stackoverflow.com/a/70552262/14582
      - name: Run tests
        run: |
          dotnet test --nologo -l:"console;verbosity=normal"
