name: Test pushes to dev

on:
  push:
    # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
    branches:
      - devzzz

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '7.0.x'
      # https://stackoverflow.com/a/70552262/14582
      - run: dotnet test --nologo -l:"console;verbosity=normal"
