name: validate

on:
  push:
    # https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
    branches:
      - dev

jobs:
  validate:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet test OkTools.sln
