<Project>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputPath>$(OkOutputPath)</OutputPath>
    <RootNamespace />

    <!-- publishing defaults -->
    <PublishDir>$(OkPublishDir)</PublishDir>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <PropertyGroup>
    <OkFeatures>$(OkFeatures);Exe</OkFeatures>
  </PropertyGroup>
  <Import Project="Library.targets" />
</Project>
