<Project>

  <!-- global -->

  <PropertyGroup>
    <PackageOutputPath>$(OkPublishDir)</PackageOutputPath>
  </PropertyGroup>

  <!-- debug support -->

  <PropertyGroup>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>embedded</DebugType>
    <EmbedAllSources>true</EmbedAllSources>
  </PropertyGroup>

  <!-- global usings -->

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>

  <!-- jetbrains annotations -->

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations">
      <PrivateAssets>all</PrivateAssets> <!-- keep out of nuget packages -->
    </PackageReference>
    <Using Include="JetBrains.Annotations" />
  </ItemGroup>

  <!-- test support -->

  <ItemGroup Condition=" Exists('$(MSBuildProjectDirectory)\$(MSBuildProjectName)-Tests.csproj') ">
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(MSBuildProjectName)-Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

<!-- << OkFeatures >> -->

  <!-- direct features: Core, Cli, -Cathode, NetMulti, T4 -->
  <!-- implicit from Tests.targets: Tests (implies Core) -->
  <!-- implicit from Exe.targets: Exe -->

  <!-- prepare OkFeatures -->
  <PropertyGroup>
    <!-- ensure we can always test for ';feature;' -->
    <OkFeatures>;$(OkFeatures);</OkFeatures>
    <!-- remove any whitespace that slipped in -->
    <OkFeatures>$([System.String]::Copy('$(OkFeatures)').Replace(' ',''))</OkFeatures>
  </PropertyGroup>

  <!-- Feature: NetMulti -->

  <PropertyGroup Condition=" $(OkFeatures.Contains(';NetMulti;')) ">
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <TargetFramework/>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>

  <!-- Feature: Core -->

  <ItemGroup Condition=" $(OkFeatures.Contains(';Core;')) ">
    <ProjectReference Include="$(OkSrcRoot)Core\Core.csproj" />
    <Using Include="OkTools.Core" />
    <Using Include="OkTools.Core.Extensions" />
    <Using Include="OkTools.Core.StaticUtility" Static="true" />
  </ItemGroup>

  <!-- Feature: Cli and -Cathode -->

  <!-- the '-Cathode' feature is meant to help libraries that are using Cli features, need to transition to Cathode, but
       haven't yet and are still using Console.* -->

  <ItemGroup Condition=" $(OkFeatures.Contains(';Cli;')) ">
    <ProjectReference Include="$(OkSrcRoot)Terminal\Terminal.csproj" />
    <PackageReference Include="docopt.net" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Vezel.Cathode" Condition=" $(OkFeatures.Contains(';-Cathode;')) == false " />
    <Using Include="OkTools.Terminal.Extensions" />
  </ItemGroup>
  <PropertyGroup Condition=" $(OkFeatures.Contains(';-Cathode;')) == true ">
    <NoWarn>$(NoWarn);RS0030</NoWarn>
  </PropertyGroup>

  <!-- Feature: BannedSymbols -->

  <ItemGroup Condition=" $(OkFeatures.Contains(';BannedSymbols;')) ">
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!-- put this in the csproj also: <AdditionalFiles Include="BannedSymbols.txt"/> -->
  </ItemGroup>

  <!-- Feature: T4 -->
  <!-- TEMPORARILY DISABLED - T4.Build does not support .NET 8 SDK, gets an error from a missing assembly.
       just go with manual Rider-based T4 for now. -->
  <!--Choose>
    <When Condition=" $(OkFeatures.Contains(';T4;')) ">
      <Choose>
        <When Condition=" $(OkFeatures.Contains(';Tests;')) ">
          <ItemGroup><None Include="*.t.tt" Generator="TextTemplatingFileGenerator" /></ItemGroup>
        </When>
        <Otherwise>
          <ItemGroup><None Include="*.tt" Generator="TextTemplatingFileGenerator" /></ItemGroup>
          </Otherwise>
      </Choose>
      <ItemGroup>
        <PackageReference Include="T4.Build" PrivateAssets="All" />
      </ItemGroup>
      <PropertyGroup>
        <TextTemplateTransformAll>false</TextTemplateTransformAll>
      </PropertyGroup>
    </When>
  </Choose-->

  <!-- dll config -->

  <PropertyGroup Condition=" !$(OkFeatures.Contains(';Exe;')) and !$(OkFeatures.Contains(';Tests;'))">
    <AssemblyName>OkTools.$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <!-- library/test split -->

  <Choose>
    <When Condition=" $(OkFeatures.Contains(';Tests;')) and !$(OkFeatures.Contains(';TestsStandalone;'))">
      <PropertyGroup>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
      </PropertyGroup>
      <ItemGroup>
        <Compile Include="**\*.t.cs" />
        <None Remove="*" />
        <None Remove="TestFiles\**" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <Compile Remove="**\*.t.*" />
        <None Remove="**\*.t.*" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <!-- platform exclusions -->

  <ItemGroup>
    <Compile Remove="*_Unix.*" Condition=" '$(OS)' == 'Windows_NT' " />
    <Compile Remove="*_Windows.*" Condition=" '$(OS)' != 'Windows_NT' " />
  </ItemGroup>

</Project>
