<Project>

  <PropertyGroup>
    <RootNamespace />
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <GenerateDependencyFile>true</GenerateDependencyFile> <!-- needed for nunit runner -->
    <RunSettingsFilePath>$(OkSrcRoot).runsettings</RunSettingsFilePath>
    <NoWarn>$(NoWarn);CA1861</NoWarn>

    <OkFeatures>$(OkFeatures);Core;Tests</OkFeatures>
    <OkBaseProjectFile>$([System.String]::Copy($(MSBuildProjectFile)).Replace('-Tests.csproj', '.csproj'))</OkBaseProjectFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'TestUtils'">
    <Compile Include="$(OkSrcRoot)_Include\TestUtils.cs">
      <Link>_Include\TestUtils.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(OkBaseProjectFile)" />

    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" /> <!-- i'm told that this also sets property IsTestProject=true -->
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Shouldly" />

    <Using Include="NUnit.Framework" />
    <Using Include="Shouldly" />
    <Using Include="System.Text" />
  </ItemGroup>

  <Import Project="Library.targets" />

  <!-- pass location of test data files into an attribute for tests to use -->
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <ItemGroup>
      <AssemblyAttributes Include="TestFilesLocationAttribute">
        <_Parameter1>$(ProjectDir)TestFiles</_Parameter1>
      </AssemblyAttributes>
    </ItemGroup>
    <WriteCodeFragment
      Condition="Exists('$(ProjectDir)TestFiles')"
      AssemblyAttributes="@(AssemblyAttributes)" Language="C#"
      OutputDirectory="$(IntermediateOutputPath)" OutputFile="BuildProperties.cs">
      <Output TaskParameter="OutputFile" ItemName="Compile" />
      <Output TaskParameter="OutputFile" ItemName="FileWrites" />
    </WriteCodeFragment>
  </Target>

</Project>
